import type { ProjectPageData } from '../project-types';

/**
 * Hello Darkness assets — mapped from Hello Darkness Photo Pairing.pdf:
 * hero = title card · shout-outs = Levon / Sam / Linney · concert ·
 * screening · Goldwyn Q&A · box-office market · film-still / Garfunkel markets.
 */
const A = '/preview/story-inc/hello-darkness';
const img = {
  heroTitle: `${A}/hero-title.png`,
  levon: `${A}/levon-hawke.jpg`,
  sam: `${A}/sam-rechner.png`,
  linney: `${A}/laura-linney.png`,
  concert: `${A}/concert.jpg`,
  screening: `${A}/screening.jpg`,
  goldwyn: `${A}/tony-goldwyn.jpg`,
  boxOffice: `${A}/box-office.jpg`,
  filmStill: `${A}/film-still.png`,
  garfunkel: `${A}/art-garfunkel.jpg`,
  /** Face-cropped for wide market media (source is a tall portrait). */
  garfunkelFace: `${A}/art-garfunkel-face.jpg`,
  setVisit: `${A}/set-visit.jpg`,
} as const;

/** Hello Darkness, My Old Friend — Story Inc client comp from partner HTML brief. */
export const HELLO_DARKNESS: ProjectPageData = {
  slug: 'hello-darkness',
  title: 'Hello Darkness, My Old Friend',
  titleLines: ['Hello Darkness,', 'My Old Friend'],
  kick: 'Coming 2027',
  castLine: ['Laura Linney', 'Sam Rechner', 'Levon Hawke'],
  credits:
    'Directed by Tony Goldwyn · Written for the screen by Tony Spiridakis · Produced by Wayfarer Studios',
  story: [
    'The True Story Behind One of the Greatest Songs Ever Recorded.',
    'In 1961, Columbia University student Sandy Greenberg — a poor kid from Buffalo with a bright future — lost his sight to a misdiagnosed illness at just nineteen. Devastated, he dropped out and nearly gave up. But his roommate wouldn\'t let him. That roommate was Art Garfunkel — yes, one half of Simon & Garfunkel — who nicknamed himself "Darkness," read Sandy his textbooks, walked him to class, and refused to let his best friend disappear.',
    'Sandy came back. He graduated Phi Beta Kappa from Columbia, earned a PhD from Harvard, and went on to become an inventor, entrepreneur, presidential adviser, and philanthropist who has devoted his life to ending blindness. Art went on to music history with Paul Simon — a career Sandy helped launch, once sending Art the $400 that was nearly all he had to chase the dream.',
    "More than sixty years later, they're still best friends. It's a true story about friendship, sacrifice, and finding the light.",
  ],
  followLine:
    'Follow this page for trailer invites, ticket windows, concert dates, and grant announcements.',
  jumpTiles: [
    { label: 'Rewards', sub: '{rewards} live drops', href: '#rewards' },
    { label: 'Markets', sub: '{markets} live now', href: '#markets' },
    { label: 'Trailers', sub: 'Watch & share', href: '#trailers' },
    { label: 'Follow page', sub: 'VIP + notifications', href: '#notify' },
  ],
  heroPoster: img.heroTitle,
  teaserLabel: 'Sizzle reel',
  // Frame.io sizzle — https://f.io/e75-cmW6
  trailerUrl: 'https://f.io/e75-cmW6',
  fanCount: 22147,
  rewardGroups: [
    {
      heading: 'Redeem with Story Cash',
      rewards: [
        {
          id: 'shout-sam',
          caption: '',
          status: 'Open now',
          title: 'Virtual shout-out — Sam Rechner',
          body: 'A personal video message from Sam Rechner.',
          color: '#000000',
          image: img.sam,
          price: '1,500 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'shout-levon',
          caption: '',
          status: 'Open now',
          title: 'Virtual shout-out — Levon Hawke',
          body: 'A personal video message from Levon Hawke.',
          color: '#000000',
          image: img.levon,
          price: '1,500 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'poster',
          caption: '',
          status: 'Open now',
          title: 'Signed movie poster',
          body: 'The one-sheet, signed. Limited run.',
          color: '#000000',
          price: '2,000 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'vinyl',
          caption: '',
          status: 'Open now',
          title: 'Soundtrack on vinyl',
          body: 'The soundtrack, pressed for Followers.',
          color: '#000000',
          price: '2,500 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'linney',
          caption: '',
          status: 'Open now',
          title: 'Video message from Laura Linney',
          body: 'A personal video message from Laura Linney.',
          color: '#000000',
          image: img.linney,
          price: '5,000 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'memoir',
          caption: '',
          status: 'Open now',
          title: 'Signed memoir',
          body: 'A signed copy of the memoir that inspired the film.',
          color: '#000000',
          price: '5,000 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'concert',
          caption: '',
          status: 'Open now',
          title: 'The Hello Darkness concert',
          body: 'Access to the benefit concert tied to the film.',
          color: '#000000',
          image: img.concert,
          price: '7,500 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'screening',
          caption: '',
          status: 'Open now',
          title: 'Private screening',
          body: 'A private screening for you and guests.',
          color: '#000000',
          image: img.screening,
          price: '15,000 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'set-visit',
          caption: '',
          status: 'Granted',
          title: 'Set visit — NYC',
          body: 'Awarded. Closed.',
          color: '#000000',
          image: img.setVisit,
          price: 'Awarded',
          priceHint: 'Closed',
        },
      ],
    },
    {
      heading: 'Drawings',
      rewards: [
        {
          id: 'qa-goldwyn',
          caption: '',
          status: 'Drawing',
          title: 'Virtual Q&A with Tony Goldwyn',
          body: 'A live virtual Q&A with the director.',
          color: '#000000',
          image: img.goldwyn,
          price: 'Free entry',
          priceHint: 'Drawing',
        },
        {
          id: 'opening-night',
          caption: '',
          status: 'Drawing',
          title: 'Two tickets to opening night',
          body: 'Two tickets to opening night.',
          color: '#000000',
          price: 'Free entry',
          priceHint: 'Drawing',
        },
      ],
    },
  ],
  markets: [
    {
      question: 'Domestic box office opening weekend?',
      outcomes: [
        { label: 'Under $4M', pct: 21 },
        { label: '$4M–$7.9M', pct: 34 },
        { label: 'Other', pct: 20 },
        { label: 'Other 2', pct: 15 },
        { label: 'Other 3', pct: 10 },
      ],
      volume: '$18.4k vol',
      traders: '1.2k',
      closes: '10.7.27',
      image: img.boxOffice,
      imagePosition: 'center',
    },
    {
      question: 'After watching the sizzle, will this be Certified Fresh?',
      outcomes: [
        { label: 'Yes', pct: 67 },
        { label: 'No', pct: 33 },
      ],
      volume: '$11.9k vol',
      traders: '0.8k',
      closes: '10.8.27',
    },
    {
      question:
        'Will "The Sound of Silence" re-enter the Billboard Hot 100 within 4 weeks of release?',
      outcomes: [
        { label: 'Yes', pct: 58 },
        { label: 'No', pct: 42 },
      ],
      volume: '$24.7k vol',
      traders: '2.1k',
      closes: '11.5.27',
    },
    {
      question:
        "How much will Simon & Garfunkel's weekly US streams rise in release week?",
      outcomes: [
        { label: 'Under 25%', pct: 18 },
        { label: '50%–99%', pct: 31 },
        { label: 'Other', pct: 20 },
        { label: 'Other 2', pct: 16 },
        { label: 'Other 3', pct: 15 },
      ],
      volume: '$16.2k vol',
      traders: '1.4k',
      closes: '10.15.27',
    },
    {
      question: 'Will it out-open A Complete Unknown?',
      outcomes: [
        { label: 'Yes', pct: 26 },
        { label: 'No', pct: 74 },
      ],
      volume: '$20.8k vol',
      traders: '1.6k',
      closes: '10.7.27',
    },
    {
      question: 'Which music-driven true story opens biggest this season?',
      outcomes: [
        { label: 'Hello Darkness', pct: 31 },
        { label: 'Other title', pct: 42 },
        { label: 'Other', pct: 12 },
        { label: 'Other 2', pct: 10 },
        { label: 'Other 3', pct: 5 },
      ],
      volume: '$14.3k vol',
      traders: '1.1k',
      closes: '10.8.27',
    },
    {
      question: 'How many Simon & Garfunkel songs are featured in the film?',
      outcomes: [
        { label: '1–2', pct: 17 },
        { label: '3–4', pct: 39 },
        { label: 'Other', pct: 18 },
        { label: 'Other 2', pct: 14 },
        { label: 'Other 3', pct: 12 },
      ],
      volume: '$31.6k vol',
      traders: '2.4k',
      closes: '10.8.27',
    },
    {
      question:
        'Will the memoir hit a national bestseller list within 4 weeks of release?',
      outcomes: [
        { label: 'Yes', pct: 52 },
        { label: 'No', pct: 48 },
      ],
      volume: '$17.8k vol',
      traders: '1.3k',
      closes: '11.5.27',
    },
    {
      question: 'How much will weekly memoir sales rise in release week?',
      outcomes: [
        { label: 'Under 50%', pct: 15 },
        { label: '100%–199%', pct: 28 },
        { label: 'Other', pct: 22 },
        { label: 'Other 2', pct: 20 },
        { label: 'Other 3', pct: 15 },
      ],
      volume: '$12.4k vol',
      traders: '0.9k',
      closes: '10.15.27',
    },
    {
      question: 'Which cut drops as the official trailer?',
      outcomes: [
        { label: 'The friendship cut', pct: 41 },
        { label: 'The music cut', pct: 34 },
        { label: 'Other', pct: 15 },
        { label: 'Other 2', pct: 10 },
      ],
      volume: '$15.1k vol',
      traders: '1.7k',
      closes: '7.16.27',
    },
    {
      question: 'Which song closes the film?',
      outcomes: [
        { label: 'The Sound of Silence', pct: 47 },
        { label: 'Bridge Over Troubled Water', pct: 29 },
        { label: 'Other', pct: 12 },
        { label: 'Other 2', pct: 8 },
        { label: 'Other 3', pct: 4 },
      ],
      volume: '$13.6k vol',
      traders: '1.0k',
      closes: '10.8.27',
    },
    {
      question: 'Does the film end in 1961, or flash forward to the present day?',
      outcomes: [
        { label: 'Present day', pct: 63 },
        { label: 'Stays in the past', pct: 37 },
      ],
      volume: '$22.1k vol',
      traders: '1.8k',
      closes: '10.8.27',
      image: img.filmStill,
      imagePosition: 'center',
    },
    {
      question: 'Does the "Darkness" nickname appear on screen?',
      outcomes: [
        { label: 'Yes', pct: 81 },
        { label: 'No', pct: 19 },
      ],
      volume: '$19.5k vol',
      traders: '1.5k',
      closes: '10.8.27',
    },
    {
      question: 'Will the real Sandy Greenberg or Art Garfunkel appear in the film?',
      outcomes: [
        { label: 'Both', pct: 22 },
        { label: 'Neither', pct: 41 },
        { label: 'Sandy only', pct: 22 },
        { label: 'Art only', pct: 15 },
      ],
      volume: '$26.9k vol',
      traders: '2.0k',
      closes: '10.8.27',
      image: img.garfunkelFace,
      imagePosition: 'center',
    },
    {
      question: 'Will the film receive an Academy Award nomination?',
      outcomes: [
        { label: 'Yes', pct: 44 },
        { label: 'No', pct: 56 },
      ],
      volume: '$28.3k vol',
      traders: '2.2k',
      closes: '12.10.27',
    },
    {
      question: 'Which festival premieres it first?',
      outcomes: [
        { label: 'Toronto', pct: 38 },
        { label: 'Sundance', pct: 26 },
        { label: 'Other', pct: 16 },
        { label: 'Other 2', pct: 12 },
        { label: 'Other 3', pct: 8 },
      ],
      volume: '$9.7k vol',
      traders: '0.7k',
      closes: '4.23.27',
    },
  ],
  comments: [
    {
      handle: '@quietbrooklyn',
      place: 'New York',
      time: '3h ago',
      initials: 'MB',
      avatarColor: '#1a86f0',
      badge: 'Holding YES @ 58¢',
      body: 'every time a movie uses a catalog song like this the streams spike for a month. the chart market is the free money on this board',
    },
    {
      handle: '@readsahead',
      place: 'Chicago',
      time: '6h ago',
      initials: 'RH',
      avatarColor: '#0c63c4',
      body: "read the memoir last year. the $400 is the whole thing. if it's not in the movie I riot",
    },
    {
      handle: '@classof09',
      place: 'Buffalo',
      time: '11h ago',
      initials: 'CL',
      avatarColor: '#2a2118',
      body: "my roommate did something like this for me sophomore year. nominated him. that's the whole reason I made an account",
    },
  ],
  trailers: [
    {
      title: 'Sizzle reel',
      meta: 'Live now · predict the opening after you watch',
      status: 'Watch',
      thumb: img.heroTitle,
    },
    {
      title: 'Fan-share invite',
      meta: 'Filmmakers invite trusted fans to share the teaser early',
      status: 'Request access',
      thumb: img.filmStill,
    },
  ],
  hasTickets: true,
  ticketsBody:
    'Followers get first access when tickets go on sale, and first word on the benefit concert.',
  studio: 'Wayfarer Studios',
  filmmakerBody:
    'A Wayfarer Studios production. Directed by Tony Goldwyn. Adapted for the screen by Tony Spiridakis, from the memoir by Sanford D. Greenberg. Shot in New York City.',
  team: [
    { name: 'Laura Linney', image: img.linney },
    { name: 'Sam Rechner', image: img.sam },
    { name: 'Levon Hawke', image: img.levon },
  ],
  notifyBody:
    "Trailer invites, ticket windows, concert dates, and grant announcements. Follow this project and we'll keep you in the loop.",
  updates: [
    {
      from: 'Wayfarer Studios',
      role: 'Updates',
      time: 'Yesterday',
      body: 'The sizzle is live for Followers before it goes anywhere else. Watch it, then tell us what you think it opens to.',
    },
    {
      from: 'Wayfarer Studios',
      role: 'Updates',
      time: '4d ago',
      body: 'The first cut is coming together. Followers get a look at footage nobody outside the edit has seen.',
    },
    {
      from: 'Wayfarer Studios',
      role: 'Updates',
      time: '1w ago',
      body: "We hosted two fans on the NYC set last month — they watched filming and met the cast. We'll be doing it again.",
    },
  ],
  footerNote:
    'Concept comp for partner discussion. All market odds, volumes, trading counts, fan counts, Story Cash prices, and fan comments are illustrative placeholders, not real data.',
};
