import type { ProjectPageData } from '../project-types';

/**
 * Notorious G.O.D. assets — mapped from Notorious GOD.pdf:
 * hero = sky title card · Rainn video · Soul Boom · screening ·
 * Pope / Tippett / Dalai Lama / Krasinski markets.
 */
const A = '/preview/story-inc/notorious-god';
const img = {
  heroTitle: `${A}/hero-title.jpg`,
  rainn: `${A}/rainn-portrait.jpg`,
  rainnGesture: `${A}/rainn-gesture.jpg`,
  rainnDoorway: `${A}/rainn-doorway.jpg`,
  soulBoom: `${A}/soul-boom.png`,
  screening: `${A}/screening.jpg`,
  pope: `${A}/pope.jpg`,
  tippett: `${A}/krista-tippett.jpg`,
  dalai: `${A}/dalai-lama-face.jpg`,
  krasinski: `${A}/krasinski-face.jpg`,
} as const;

/** The Notorious G.O.D. — Story Inc client comp from partner HTML brief. */
export const NOTORIOUS_GOD: ProjectPageData = {
  slug: 'notorious-god',
  title: 'The Notorious G.O.D.',
  titleLines: ['The Notorious', 'G.O.D.'],
  tagline: 'Why do human beings need God?',
  kick: 'Coming 2027',
  castLine: ['Hosted by Rainn Wilson', 'Directed by Penny Lane'],
  credits: 'Fully funded by The John Templeton Foundation',
  story: [
    'Rather than offering answers, the film invites curiosity.',
    'Long before he founded SoulPancake or wrote the bestseller Soul Boom, Rainn Wilson was asking one question: why do human beings need God? This documentary follows his own search around the world — believers, skeptics, scientists, clergy, artists, and seekers — in an honest, funny, and profoundly human conversation about faith, doubt, and meaning.',
    "Playful and sincere at once, it takes up the call for cinema to be a workshop of hope: a film that helps people contemplate their own lives, wrestle with humanity's oldest questions, and bear witness to beauty and truth. Directed by Penny Lane, whose documentaries have made a career out of asking uncomfortable questions with a straight face and a sense of humor.",
  ],
  followLine:
    'Follow this page for interview reveals, festival news, distribution announcements, and reward drops.',
  jumpTiles: [
    { label: 'Rewards', sub: '{rewards} live drops', href: '#rewards' },
    { label: 'Markets', sub: '{markets} live now', href: '#markets' },
    { label: 'Trailers', sub: 'Watch & share', href: '#trailers' },
    { label: 'Follow page', sub: 'VIP + notifications', href: '#notify' },
  ],
  heroPoster: img.heroTitle,
  teaserLabel: 'Teaser or sizzle',
  fanCount: 26382,
  rewardGroups: [
    {
      heading: 'Redeem with Story Cash',
      rewards: [
        {
          id: 'cut-scenes',
          caption: '',
          status: 'Open now',
          title: "Didn't make the cut",
          body: 'Scenes and moments that did not make the final film.',
          color: '#000000',
          price: '1,000 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'wisdom',
          caption: '',
          status: 'Open now',
          title: 'Words of wisdom',
          body: 'A collection of hard-won lines from the road.',
          color: '#000000',
          price: '2,000 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'rainn-video',
          caption: '',
          status: 'Signature reward',
          title: 'A video from Rainn',
          body: 'A personal video reply from Rainn Wilson.',
          color: '#000000',
          image: img.rainn,
          imagePosition: 'center',
          price: '2,500 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'soul-boom',
          caption: '',
          status: 'Open now',
          title: 'Soul Boom, signed',
          body: 'A signed copy of Soul Boom.',
          color: '#000000',
          image: img.soulBoom,
          imagePosition: 'center',
          price: '3,500 SC',
          priceHint: 'Redeem',
        },
        {
          id: 'screening',
          caption: '',
          status: 'Open now',
          title: 'Private screening + guide',
          body: 'A private screening with a discussion guide.',
          color: '#000000',
          image: img.screening,
          imagePosition: 'center',
          price: '15,000 SC',
          priceHint: 'Redeem',
        },
      ],
    },
    {
      heading: 'Drawings',
      rewards: [
        {
          id: 'hour-rainn',
          caption: '',
          status: 'Drawing',
          title: 'An hour with Rainn Wilson',
          body: 'A live hour with Rainn Wilson.',
          color: '#000000',
          image: img.rainn,
          imagePosition: 'center',
          price: 'Free entry',
          priceHint: 'Drawing',
        },
        {
          id: 'premiere',
          caption: '',
          status: 'Drawing',
          title: 'Two seats at the premiere',
          body: 'Two seats at the premiere.',
          color: '#000000',
          price: 'Free entry',
          priceHint: 'Drawing',
        },
      ],
    },
  ],
  markets: [
    {
      question: 'Will Rainn interview the Dalai Lama?',
      outcomes: [
        { label: 'Yes', pct: 38 },
        { label: 'No', pct: 62 },
      ],
      volume: '$44.2k vol',
      traders: '3.6k',
      closes: '9.10.27',
      image: img.dalai,
      imagePosition: 'center',
    },
    {
      question: 'Which of these appear in the film?',
      outcomes: [
        { label: "Alex O'Connor", pct: 64 },
        { label: 'Krista Tippett', pct: 41 },
        { label: 'Other', pct: 12 },
        { label: 'Other 2', pct: 10 },
        { label: 'Other 3', pct: 8 },
        { label: 'Other 4', pct: 6 },
        { label: 'Other 5', pct: 5 },
        { label: 'Other 6', pct: 4 },
        { label: 'Other 7', pct: 3 },
        { label: 'Other 8', pct: 2 },
      ],
      volume: '$38.7k vol',
      traders: '3.1k',
      closes: '9.10.27',
      image: img.tippett,
      imagePosition: 'center',
    },
    {
      question: 'Will Rainn get an audience with the Pope?',
      outcomes: [
        { label: 'Yes', pct: 21 },
        { label: 'No', pct: 79 },
      ],
      volume: '$29.4k vol',
      traders: '2.4k',
      closes: '9.10.27',
      image: img.pope,
      imagePosition: 'center',
    },
    {
      question: 'How many faith traditions are represented on screen?',
      outcomes: [
        { label: 'Under 5', pct: 14 },
        { label: '8–10', pct: 33 },
        { label: 'Other', pct: 22 },
        { label: 'Other 2', pct: 18 },
        { label: 'Other 3', pct: 13 },
      ],
      volume: '$17.3k vol',
      traders: '1.4k',
      closes: '9.10.27',
    },
    {
      question: 'How many countries does the film visit?',
      outcomes: [
        { label: '1–3', pct: 12 },
        { label: '7–9', pct: 29 },
        { label: 'Other', pct: 24 },
        { label: 'Other 2', pct: 20 },
        { label: 'Other 3', pct: 15 },
      ],
      volume: '$13.8k vol',
      traders: '1.1k',
      closes: '9.10.27',
    },
    {
      question: 'Will a former Office castmate appear on camera?',
      outcomes: [
        { label: 'Yes', pct: 47 },
        { label: 'No', pct: 53 },
      ],
      volume: '$21.6k vol',
      traders: '1.9k',
      closes: '9.10.27',
      image: img.krasinski,
      imagePosition: 'center',
    },
    {
      question: 'Theatrical release first, or straight to streaming?',
      outcomes: [
        { label: 'Theatrical first', pct: 57 },
        { label: 'Streaming first', pct: 43 },
      ],
      volume: '$26.1k vol',
      traders: '2.2k',
      closes: '3.5.27',
    },
    {
      question: 'Which platform picks it up?',
      outcomes: [
        { label: 'Netflix', pct: 26 },
        { label: 'Apple TV+', pct: 19 },
        { label: 'Other', pct: 18 },
        { label: 'Other 2', pct: 12 },
        { label: 'Other 3', pct: 10 },
        { label: 'Other 4', pct: 7 },
        { label: 'Other 5', pct: 5 },
        { label: 'Other 6', pct: 3 },
      ],
      volume: '$23.9k vol',
      traders: '2.0k',
      closes: '3.5.27',
    },
    {
      question: 'Which festival premieres it?',
      outcomes: [
        { label: 'Sundance', pct: 34 },
        { label: 'SXSW', pct: 22 },
        { label: 'Other', pct: 18 },
        { label: 'Other 2', pct: 14 },
        { label: 'Other 3', pct: 8 },
        { label: 'Other 4', pct: 4 },
      ],
      volume: '$15.7k vol',
      traders: '1.3k',
      closes: '1.15.27',
    },
    {
      question: 'Domestic opening weekend, if it goes theatrical?',
      outcomes: [
        { label: 'Under $250K', pct: 24 },
        { label: '$250K–$749K', pct: 31 },
        { label: 'Other', pct: 20 },
        { label: 'Other 2', pct: 15 },
        { label: 'Other 3', pct: 10 },
      ],
      volume: '$19.2k vol',
      traders: '1.5k',
      closes: '9.9.27',
    },
    {
      question: 'Will it become the highest-grossing documentary of its year?',
      outcomes: [
        { label: 'Yes', pct: 18 },
        { label: 'No', pct: 82 },
      ],
      volume: '$11.4k vol',
      traders: '0.9k',
      closes: '12.31.27',
    },
    {
      question: 'Will it make the Academy Award documentary shortlist?',
      outcomes: [
        { label: 'Yes', pct: 39 },
        { label: 'No', pct: 61 },
      ],
      volume: '$16.8k vol',
      traders: '1.4k',
      closes: '12.16.27',
    },
    {
      question: 'Tomatometer score one week after release?',
      outcomes: [
        { label: 'Under 70%', pct: 16 },
        { label: '80%–89%', pct: 32 },
        { label: 'Other', pct: 22 },
        { label: 'Other 2', pct: 18 },
        { label: 'Other 3', pct: 12 },
      ],
      volume: '$14.5k vol',
      traders: '1.2k',
      closes: '9.17.27',
    },
    {
      question: 'Will Soul Boom re-enter a national bestseller list after release?',
      outcomes: [
        { label: 'Yes', pct: 49 },
        { label: 'No', pct: 51 },
      ],
      volume: '$10.3k vol',
      traders: '0.8k',
      closes: '10.8.27',
    },
    {
      question: 'Does the film end with an answer, or a question?',
      outcomes: [
        { label: 'A question', pct: 71 },
        { label: 'An answer', pct: 29 },
      ],
      volume: '$33.5k vol',
      traders: '2.8k',
      closes: '9.10.27',
    },
  ],
  comments: [
    {
      handle: '@cosmicadjacent',
      place: 'Portland',
      time: '2h ago',
      initials: 'CS',
      avatarColor: '#2E3192',
      badge: 'Holding YES @ 64¢',
      body: "he already sat down with Alex O'Connor for the newsletter. that one's basically resolved, people are just slow",
    },
    {
      handle: '@pewfour',
      place: 'Nashville',
      time: '5h ago',
      initials: 'PW',
      avatarColor: '#A87C1F',
      body: 'Penny Lane made Hail Satan? and Confessions of a Good Samaritan. she is not going to end this thing with a tidy answer. loading QUESTION',
    },
    {
      handle: '@doubtkid',
      place: 'Chicago',
      time: '9h ago',
      initials: 'DK',
      avatarColor: '#D6296B',
      body: "Templeton money means it goes wide and free eventually. streaming first, I'd bet the house",
    },
  ],
  trailers: [
    {
      title: 'First look',
      meta: 'Live now · predict after you watch',
      status: 'Watch',
      thumb: img.heroTitle,
    },
    {
      title: 'Uncut conversations',
      meta: "Full-length interviews that won't fit in the film",
      status: 'Request access',
      thumb: img.rainnDoorway,
    },
  ],
  hasTickets: true,
  ticketsBody:
    'Followers get first word on the festival premiere, distribution, and where to see it.',
  studio: 'The Notorious G.O.D.',
  filmmakerBody:
    'Hosted by Rainn Wilson — actor, writer, founder of SoulPancake, and author of the New York Times bestseller Soul Boom. Directed by Penny Lane, whose documentaries include Our Nixon, Hail Satan?, and Confessions of a Good Samaritan. Fully funded by The John Templeton Foundation.',
  team: [
    { name: 'Rainn Wilson', image: img.rainn },
    { name: 'Penny Lane' },
  ],
  notifyBody:
    "Interview reveals, festival news, distribution announcements, and reward drops. Follow this project and we'll keep you in the loop.",
  updates: [
    {
      from: 'Rainn Wilson',
      role: 'Host',
      time: 'Yesterday',
      body: "Just wrapped a conversation I did not expect to go where it went. Can't say who yet. The interview market closes when we announce — you've been warned.",
    },
    {
      from: 'Penny Lane',
      role: 'Director',
      time: '4d ago',
      body: 'Three countries in eleven days. Followers get the outtakes before anyone.',
    },
    {
      from: 'Rainn Wilson',
      role: 'Host',
      time: '1w ago',
      body: 'Somebody asked me a question this week that I have not stopped thinking about. It may end up in the film.',
    },
  ],
  footerNote:
    'Concept comp for partner discussion. All market odds, volumes, trading counts, fan counts, Story Cash prices, and fan comments are illustrative placeholders, not real data. Interview subjects listed in markets are proposed options, not confirmed participants.',
};
